behavior:
  error_probability:
    '500': 0.02
    '503': 0.01
description: Apache 2.4.41 on Ubuntu 20.04
error_pages:
  '404':
    template: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

      <html><head><title>404 Not Found</title></head><body>

      <h1>Not Found</h1>

      <p>The requested URL {{path}} was not found on this server.</p>

      <hr><address>Apache/2.4.41 (Ubuntu) Server at {{host}} Port {{port}}</address>

      </body></html>'
    title: 404 Not Found
headers:
  server: Apache/2.4.41 (Ubuntu)
  x_powered_by: PHP/7.4.3
name: apache_2_4_ubuntu
timing:
  base_response_time:
    max: 0.3
    min: 0.05
  error_responses:
    '404':
      max: 1.5
      min: 0.8
    '500':
      max: 2.0
      min: 1.0
vulnerable_paths:
- description: WordPress admin panel
  path: /wp-admin/
  response_type: login_form
  threat_score: 40
- description: Generic admin panel
  path: /admin/
  response_type: login_form
  threat_score: 45
- description: PHPMyAdmin interface
  path: /phpmyadmin/
  response_type: login_form
  threat_score: 60
