# config/profiles/nginx.yaml
# Nginx 1.18 Server Profile for Realistic Deception

name: "nginx_1_18_ubuntu"
description: "Nginx 1.18.0 on Ubuntu 20.04 with Node.js/PHP"

# HTTP Headers
headers:
  server: "nginx/1.18.0"
  x_powered_by: "Express"
  x_frame_options: "SAMEORIGIN"
  x_content_type_options: "nosniff"
  strict_transport_security: "max-age=31536000; includeSubDomains"

# Response Timing (seconds) - Nginx is typically faster
timing:
  base_response_time:
    min: 0.02
    max: 0.15
  error_responses:
    404:
      min: 0.4
      max: 0.8
    403:
      min: 0.2
      max: 0.5
    500:
      min: 0.6
      max: 1.2
    502:
      min: 0.8
      max: 1.5
    503:
      min: 0.05
      max: 0.2

# Error Page Templates - Nginx style
error_pages:
  404:
    title: "404 Not Found"
    template: |
      <html>
      <head><title>404 Not Found</title></head>
      <body bgcolor="white">
      <center><h1>404 Not Found</h1></center>
      <hr><center>nginx/1.18.0</center>
      </body>
      </html>
  
  403:
    title: "403 Forbidden"
    template: |
      <html>
      <head><title>403 Forbidden</title></head>
      <body bgcolor="white">
      <center><h1>403 Forbidden</h1></center>
      <hr><center>nginx/1.18.0</center>
      </body>
      </html>
  
  500:
    title: "500 Internal Server Error"
    template: |
      <html>
      <head><title>500 Internal Server Error</title></head>
      <body bgcolor="white">
      <center><h1>500 Internal Server Error</h1></center>
      <hr><center>nginx/1.18.0</center>
      </body>
      </html>

  502:
    title: "502 Bad Gateway"
    template: |
      <html>
      <head><title>502 Bad Gateway</title></head>
      <body bgcolor="white">
      <center><h1>502 Bad Gateway</h1></center>
      <hr><center>nginx/1.18.0</center>
      </body>
      </html>

# Vulnerable Paths & Honeypots
vulnerable_paths:
  # Node.js/Express applications
  - path: "/admin/"
    description: "Admin panel"
    threat_score: 45
    response_type: "login_form"
    
  - path: "/api/"
    description: "API endpoints"
    threat_score: 30
    response_type: "json_error"
    
  - path: "/graphql"
    description: "GraphQL endpoint"
    threat_score: 50
    response_type: "graphql_introspection"
    
  # Common Node.js paths
  - path: "/node_modules/"
    description: "Node modules exposure"
    threat_score: 60
    response_type: "directory_listing"
    
  - path: "/package.json"
    description: "Package manifest"
    threat_score: 40
    response_type: "json_file"
    
  - path: "/.env"
    description: "Environment variables"
    threat_score: 85
    response_type: "env_file"
    
  # Docker/container paths
  - path: "/docker-compose.yml"
    description: "Docker compose file"
    threat_score: 70
    response_type: "yaml_file"
    
  - path: "/Dockerfile"
    description: "Docker build file"
    threat_score: 60
    response_type: "text_file"
    
  # Common web paths
  - path: "/dashboard/"
    description: "Dashboard interface"
    threat_score: 40
    response_type: "login_form"
    
  - path: "/upload/"
    description: "File upload endpoint"
    threat_score: 55
    response_type: "upload_form"
    
  - path: "/config/"
    description: "Configuration directory"
    threat_score: 65
    response_type: "403_error"
    
  # Git exposure
  - path: "/.git/"
    description: "Git repository"
    threat_score: 80
    response_type: "directory_listing"
    
  - path: "/.gitignore"
    description: "Git ignore file"
    threat_score: 25
    response_type: "text_file"

# Directory Listing Behavior
directory_listing:
  enabled: false  # Nginx typically disables autoindex
  show_hidden_files: false
  default_index_files: ["index.html", "index.htm", "index.php", "index.js"]

# Behavioral Patterns
behavior:
  # Response probability (0.0 - 1.0)
  error_probability:
    500: 0.01   # 1% chance of 500 error
    502: 0.015  # 1.5% chance of 502 (bad gateway)
    503: 0.005  # 0.5% chance of 503 error
    timeout: 0.003  # 0.3% chance of timeout
  
  # Rate limiting simulation (nginx is good at this)
  rate_limiting:
    enabled: true
    max_requests_per_minute: 120
    burst_allowance: 20
    ban_duration: 600  # 10 minutes
  
  # Session behavior
  sessions:
    cookie_name: "connect.sid"  # Express default
    session_timeout: 3600  # 1 hour
    regenerate_on_login: true

# Security Features
security_headers:
  x_frame_options: "SAMEORIGIN"
  x_content_type_options: "nosniff"
  x_xss_protection: "1; mode=block"
  strict_transport_security: "max-age=31536000; includeSubDomains"
  referrer_policy: "strict-origin-when-cross-origin"
  content_security_policy: "default-src 'self'"

# File Upload Handling
file_uploads:
  max_file_size: "10M"
  allowed_extensions: [".jpg", ".jpeg", ".png", ".gif", ".pdf", ".txt", ".json"]
  upload_directory: "/var/www/uploads/"
  temp_directory: "/tmp/nginx_uploads/"

# Log Patterns
log_patterns:
  access_log_format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"'
  error_log_format: '$time_iso8601 [error] $pid#$tid: *$connection $message'

# Common Nginx Modules
modules:
  - http_ssl_module
  - http_realip_module
  - http_addition_module
  - http_geoip_module
  - http_gunzip_module
  - http_gzip_static_module
  - http_image_filter_module
  - http_v2_module
  - http_sub_module
  - http_dav_module
  - http_flv_module
  - http_mp4_module
  - http_random_index_module
  - http_secure_link_module
  - http_stub_status_module

# SSL/TLS Configuration (Nginx style)
ssl:
  protocols: ["TLSv1.2", "TLSv1.3"]
  ciphers: [
    "ECDHE-ECDSA-AES128-GCM-SHA256",
    "ECDHE-RSA-AES128-GCM-SHA256",
    "ECDHE-ECDSA-AES256-GCM-SHA384",
    "ECDHE-RSA-AES256-GCM-SHA384"
  ]
  prefer_server_ciphers: true
  session_cache: "shared:SSL:10m"
  session_timeout: "10m"
  
# Reverse Proxy Behavior
proxy:
  backend_timeout: 60
  connect_timeout: 5
  read_timeout: 60
  send_timeout: 60
  buffer_size: "4k"
  
# Fingerprinting Resistance
anti_fingerprinting:
  vary_response_times: true
  randomize_error_messages: false
  hide_server_tokens: false  # Default shows version
  fake_load_behavior: true
  simulate_backend_errors: true  # 502/503 errors
