attack_types:
  exploitation:
    indicators:
    - shell.php
    - cmd.php
    - eval(
    score: 90
  reconnaissance:
    indicators:
    - robots.txt
    - sitemap.xml
    - /.well-known/
    score: 20
  vulnerability_scanning:
    indicators:
    - nikto
    - dirb
    - gobuster
    score: 40
threat_scoring:
  thresholds:
    critical: 95
    high: 85
    low: 30
    medium: 60
  weights:
    data_exfiltration: 0.1
    persistence_attempts: 0.2
    tool_detection: 0.3
    vulnerability_score: 0.4
