attack_patterns:
  sql_injection:
    patterns:
    - ''' OR 1=1--'
    - UNION SELECT
    - '''; DROP TABLE'
    response_delay: 2.5
    threat_score: 80
  xss:
    patterns:
    - <script>alert(
    - 'javascript:'
    - onerror=
    response_type: reflected_xss
    threat_score: 60
cve_simulations:
  CVE-2021-41773:
    description: Apache HTTP Server Path Traversal
    paths:
    - /cgi-bin/.%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd
    response_type: path_traversal
    threat_score: 95
tool_signatures:
  nmap:
    patterns:
    - OPTIONS *
    - GET / HTTP/1.0
    threat_score: 40
    user_agents:
    - Nmap Scripting Engine
  sqlmap:
    threat_score: 85
    user_agents:
    - sqlmap/
    - 'User-Agent: sqlmap'
